# Data Analysis Numpy & CSV's

## Tasks Today:

1) <b>Numpy</b> <br>
 &nbsp;&nbsp;&nbsp;&nbsp; a) Python List Comparison <br>
 &nbsp;&nbsp;&nbsp;&nbsp; b) In-Class Exercise #1 <br>
 &nbsp;&nbsp;&nbsp;&nbsp; c) Importing <br>
 &nbsp;&nbsp;&nbsp;&nbsp; d) Creating an NDArray <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.array() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.zeros() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.ones() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.arange() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Making Lists into NDArrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp; e) Performing Calculations on NDArrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Summation <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Difference <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Multiplication <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Division <br>
 &nbsp;&nbsp;&nbsp;&nbsp; f) Numpy Subsetting <br>
 &nbsp;&nbsp;&nbsp;&nbsp; g) Multi-dimensional Arrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp; h) Indexing NDArrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp; i) Checking NDArray Type <br>
 &nbsp;&nbsp;&nbsp;&nbsp; j) Altering NDArray Type <br>
 &nbsp;&nbsp;&nbsp;&nbsp; k) Checking the Shape <br>
 &nbsp;&nbsp;&nbsp;&nbsp; l) Altering the Shape <br>
 &nbsp;&nbsp;&nbsp;&nbsp; m) In-Class Exercise #2 <br>
 &nbsp;&nbsp;&nbsp;&nbsp; n) Complex Indexing & Assigning <br>
 &nbsp;&nbsp;&nbsp;&nbsp; o) Elementwise Multplication <br>
 &nbsp;&nbsp;&nbsp;&nbsp; p) np.where() <br>
 &nbsp;&nbsp;&nbsp;&nbsp; q) Random Sampling <br>

2) <b>Working With CSV's</b> <br>
 &nbsp;&nbsp;&nbsp;&nbsp; a) Imports <br>
 &nbsp;&nbsp;&nbsp;&nbsp; b) Reading a CSV <br>
 &nbsp;&nbsp;&nbsp;&nbsp; c) Loading a CSV's Data <br>
 &nbsp;&nbsp;&nbsp;&nbsp; d) Checking Number of Records <br>
 
3) <b>Exercises</b> <br>
 &nbsp;&nbsp;&nbsp;&nbsp; a) #1 - Calculate BMI with NDArrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp; b) #2 - Find the Average Sum of Marathon Runners <br>
 &nbsp;&nbsp;&nbsp;&nbsp; c) #3 - Random Matrix Function <br>
 &nbsp;&nbsp;&nbsp;&nbsp; d) #4 - Comparing Boston Red Sox Hitting Numbers <br>

## Numpy <br>

<p>NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.</p>
<ul>
    <li>Shape = Rows & Columns</li>
    <li>Matrix = Entire Array</li>
    <li>Vector = Variables to be applied (same vector as the one used in physics)</li>
    <li>Array = Similar to lists</li>
</ul>

#### Python List Comparison

<p>Lists are flexible, dynamic python objects that do their job quite well. But they do not support some mathematical operations in an intuitive way. Consider the summation of two lists, $l_1$ and $l_2$</p>

In [3]:
# create two lists and sum both of them together (results may not be what you expect)
l_1 = [1,2,3]
l_2 = [4,5,6]

print(f'Sum of {l_1} + {l_2} using python operators in one line {l_1 + l_2}')
#print(f'Sum of {l_1} - {l_2} using python operators in one line {l_1 - l_2}')

Sum of [1, 2, 3] + [4, 5, 6] using python operators in one line [1, 2, 3, 4, 5, 6]


<p>If we wanted to sum lists elementwise, we could write our own function that does the job entirely within the framework of python</p>

#### In-Class Exercise #1 - Write a function that sums the indexes of two lists <br>
<p>Ex: [2, 3, 4] + [1, 5, 2] = [3, 8, 6]</p>

In [7]:
# output = [3,8,6]

def sumlist(list1,list2):
    final = []
    i = 0
    while i < len(list1):
        final.append(list1[i] + list2[i])
        i += 1
    return final
sumlist([2,3,4], [1,5,2])

#OR

def listSum(list1, list2):
    list3 = []
    for i in range(len(list1)):
        list3.append(list1[i] + list2[i])
    return list3
listSum([2,3,4], [1,5,2])

[3, 8, 6]

#### Importing

In [9]:
# always import as np, standard across all of data science/analysis
#!pip install numpy
import numpy as np

#### Creating an NDArray <br>
<p>NumPy is based around a class called the $\textit{NDArray}$, which is a flexible vector / matrix class that implements the intuitive matrix and vector arithmatic lacking in basic Python. Let's start by creating some NDArrays:</p>

###### - np.array()

In [12]:
arr_1 = [0,1,2,3]

new_arr = np.array(arr_1)

print(arr_1)
print(new_arr)
type(new_arr)

[0, 1, 2, 3]
[0 1 2 3]


numpy.ndarray

###### - np.zeros()

In [13]:
# Shape -- np.zeros() has a parameter of "shape" that must be given
arr_zeros = np.zeros((3,3))
arr_zeros


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

###### - np.ones()

In [17]:
arr_ones = np.ones((3,3), int)
arr_ones_flt = np.ones((3,3))
arr_ones
arr_ones_flt

# notice no dots after the numbers, because we specified the datatype to be integer

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

###### - np.arange()

In [19]:
arr_range= np.arange(1,10)
arr_range

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

###### - Making Lists into NDArrays

In [21]:
some_list = [99,14,7]
numpy_array = np.array(some_list)
numpy_array

np_arr_2 = np.array([99,14,7])
np_arr_2

array([99, 14,  7])


#### Performing Calculations on NDArrays


###### - Summation

In [24]:
np_list = np.array([5,10,15,20,25,30])
np_list_2 = np.array([10,20,30,40,50,60])

result_sum = np_list + np_list_2
result_sum

array([15, 30, 45, 60, 75, 90])

###### - Difference

In [25]:
result_diff = np_list - np_list_2
result_diff

array([ -5, -10, -15, -20, -25, -30])

###### - Multiplication

In [26]:
result_prod = np_list * np_list_2
result_prod

array([  50,  200,  450,  800, 1250, 1800])

###### - Division

In [27]:
result_div = np_list / np_list_2
result_div

array([0.5, 0.5, 0.5, 0.5, 0.5, 0.5])

#### Modulo

In [31]:
result_mod = np_list % np_list_2
result_mod
result_mod.dtype

dtype('int32')

#### Floor Division

In [40]:
result_floor = np_list // np_list_2
result_floor



array([0, 0, 0, 0, 0, 0], dtype=int32)

#### Numpy Subsetting

In [58]:
print(result_prod)
print(result_prod <= 800)



test_ndStrings = np.array(['Bob','Mark','Angelica','Barb'])
print(test_ndStrings[test_ndStrings == 'Bob'])
for name in test_ndStrings:
    if name[0] == 'B':
        print(name)




test_nums = np.array([1,2,3,4,5])
new_nums = test_nums[test_nums < 5]
print(new_nums)



# conditional check, returns true or false
# print(arr1 < 2)
# print(arr2 >= 2)

# conditional check, that returns the elements that meet the given condition
np.array([name for name in test_ndStrings if name[0] == 'B'])

[  50  200  450  800 1250 1800]
[ True  True  True  True False False]
['Bob']
Bob
Barb
[1 2 3 4]


array(['Bob', 'Barb'], dtype='<U4')

#### Multi-dimensional Arrays <br>
<p>NumPy seamlessly supports multidimensional arrays and matrices of arbitrary dimension without nesting NDArrays. NDArrays themselves are flexible and extensible and may be defined with such dimensions, with a rich API of common functions to facilitate their use. Let's start by building a two dimensional 3x3 matrix by conversion from a nested group of core python lists $M = [l_0, l_1, l_2]$:</p>

In [65]:
aList = [0,1,2]
bList = [3,4,5]
cList = [6,7,8]

# first step: convert lists into a Matrix
M = [aList, bList, cList]
M
print(M[2][0])


# second step: place Matrix inside NDArray
ND_M = np.array(M)
ND_M

6


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Indexing NDArrays <br>
<p> Similar to lists within lists; however, the syntax looks more like C programming language.... It is [1, 2] to access the second row, third element.</p>

In [67]:
# in order to grab the 0th index from the 3rd row
ND_M[2,0]

6

#### Assigning Values in NDArrays

In [73]:
# Changing / assigning value
ND_M[2,0]=10
ND_M

ND_M[2,0]=8
ND_M

array([[0, 1, 2],
       [3, 4, 5],
       [8, 7, 8]])

<p>Notice above how we ended up with a 1 in the target element's place. This is a data type issue. The .dtype() method is supported by all NDArrays, as well as the .astype() method for casting between data types:</p>

#### Checking NDArray Type

In [74]:
# usind the .dtype() method
nd_type = ND_M.dtype
nd_type


dtype('int32')

#### Altering NDArray Type

In [96]:
print(nd_type)

#creating new array and changing data type
changed = ND_M.astype(np.float32)


#dtype of new matrix is float 32
changed.dtype


int32


dtype('float32')

In [ ]:
# Checking the Shape of the ND_M Numpy Array
# Using the method .shape


#### Checking the Shape <br>
<p>The behavior and properties of an NDArray are often sensitively dependent on the $\textit{shape}$ of the NDArray itself. The shape of an array can be found by calling the .shape method, which will return a tuple containing the array's dimensions:</p>

In [94]:
 # shape is always rows x columns
# Checking the Shape of the ND_M Numpy Array
# Using the method .shape

# print(type(result_changed.shape))

changed.shape
ND_M.shape

(3, 3)

#### Altering the Shape <br>
<p>As long as the number of elements remains fixed, we can reshape NDArrays at will:</p>

In [97]:
# Change the shape of the numpy array
# Using the method .reshape()

# The reshape should be a multiple of the original shape
# Meaning we can have a shape of (1,9) or (9,1) or (3,3)

# (9,1) == 9 rows , 1 column

print(changed)

#
new = changed.reshape(9,1)
new

[[0. 1. 2.]
 [3. 4. 5.]
 [8. 7. 8.]]


array([[0.],
       [1.],
       [2.],
       [3.],
       [4.],
       [5.],
       [8.],
       [7.],
       [8.]], dtype=float32)

In [ ]:
# keep in mind that the shape numbers do matter, (9, 1) is different than (1, 9)


#### In-Class Exercise #2 - Create a matrix of range 0 up to 16 and reshape it into a 4x4 matrice

In [103]:
"""
OUTPUT
    array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])
"""
ans = np.arange(16).reshape(4,4)
ans


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### Complex Indexing & Assinging

In [131]:
m2 = np.zeros((6,6))
print(m2)

# Set every first element in each row to 1
m2[:,0]=1
print(m2)

# Set all elements in axis 3 to 5 (Excluding 5) to be equal to the number 5
m2[3:5,:] = 5
print(m2)

# reset the matrix back to 0
m2 = m2 * 0
print(m2)

# Set the second and third columns to a number == 2
m2[:, 1:3] = 2
print('\n Assigning 2 to the second and third rows')
print(m2)


# Creating a vector in numpy
x = np.arange(6)
print(x)

# Reset the Matrix to 0
m2 = m2 * 0

# Set the first row to that range of vector numbers we just created
m2[:,0] = x
print(m2)


#adding a vector as the last row.
# np.append(m2,[x],axis=0)
#################
# M[rows,columns]
#################

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]
[[1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]
 [1. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

 Assigning 2 to the second and third rows
[[0. 2. 2. 0. 0. 0.]
 [0. 2. 2. 0. 0. 0.]
 [0. 2. 2. 0. 0. 0.]
 [0. 2. 2. 0. 0. 0.]
 [0. 2. 2. 0. 0. 0.]
 [0. 2. 2. 0. 0. 0.]]
[0 1 2 3 4 5]
[[0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [2. 0. 0. 0. 0. 0.]
 [3. 0. 0. 0. 0. 0.]
 [4. 0. 0. 0. 0. 0.]
 [5. 0. 0. 0. 0. 0.]]


#### Elementwise Multiplication

<p>As long as the shapes of NDArrays are 'compatible', they can be multiplied elementwise, broadcasted, used in inner products, and much much more. 'Compatible' in this context can mean compatible in the linear algebraic sense, i.e. for inner products and other matrix multiplication, or simply sharing a dimension in such a manner that broadcasting 'makes sense'. Here are some examples of this:</p>

In [132]:
# Initialize a vector of range 6, then reset Matrix to zero and run vector multiplication on the matrix
v = m2[:,:] 
v = v * 0   # or v *=0
print(m2)

# changing bottom row to be full of 2's

v[5,:]  = 2
print(v)

new_matrix = m2 * v
print(new_matrix)

# Reset the Matrix to 0


[[0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [2. 0. 0. 0. 0. 0.]
 [3. 0. 0. 0. 0. 0.]
 [4. 0. 0. 0. 0. 0.]
 [5. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [2. 2. 2. 2. 2. 2.]]
[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [10.  0.  0.  0.  0.  0.]]


#### np.where() <br>
<p>If statement within NDArrays that allows you to run conditionals on the entire array</p>

In [135]:
new_arr = np.array([400,500,600,700])
print(new_arr)
print(np.where(new_arr<600))

# Transform Data based on boolean mask == True

new_arr[np.where(new_arr < 600)] == 400

#subsetting syntax
new_arr[new_arr <600]

[400 500 600 700]
(array([0, 1], dtype=int64),)


array([400, 500])

#### Random Sampling <br>
<p>NumPy provides machinery to work with random numbers - something often needed in a broad spectrum of data science applications.</p>

In [144]:
# np.random.uniform()

# A single call generates a single random number between 0 and 1

print('Here is a random number: %s' % np.random.uniform())

# You can also pass some parameters or bounds

print('Here is a random number between 0 and 1 Million: %s' % np.random.randint(0, 1e6))

# You can also generate a bunch of random numbers all at once

print('Here are 5 random numbers between 0 and 10: %s' % np.random.uniform(0, 10, 5))

# Even matrices with shapes as a parameter

print('Here is a 3x3 matrix with numbers between 0 and 10: \n %s' % np.random.randint(0, 10, (3, 3)))

Here is a random number: 0.44193324426875324
Here is a random number between 0 and 1 Million: 576255
Here are 5 random numbers between 0 and 10: [2.31811306 9.15057877 2.15065499 0.15910663 8.49484706]
Here is a 3x3 matrix with numbers between 0 and 10: 
 [[2 7 6]
 [5 0 7]
 [2 6 6]]


## Working With CSV's

#### Imports

In [145]:
import csv
import numpy as np
from datetime import datetime

#### Reading a CSV

In [148]:
# Creating Function to open and read CSV data
def open_csv(filepath, d = ','):
    #initiate an empty dataset
    data = []
    with open(filepath, encoding = 'utf-8') as myData:
        #use csv reader from docs to parse through comma sep values
        info = csv.reader(myData, delimiter = d)
        print(info)
        
        #loop over information and append to data list
        for row in info:
            data.append(row)
    return data

#our our function to open marathon 2017

csv_data = open_csv('../files/boston_marathon2017_edited.csv')
csv_data[1:5]

[['12/30/1899 12:30:28 AM',
  '12/30/1899 12:45:44 AM',
  '12/30/1899 1:01:15 AM',
  '12/30/1899 1:16:59 AM',
  '12/30/1899 1:33:01 AM',
  '12/30/1899 1:48:19 AM',
  '12/30/1899 2:02:53 AM',
  '12/30/1899 12:15:25 AM',
  '24',
  '11',
  '7777',
  'KEN',
  '7777',
  '',
  'Keringet',
  'KEN',
  '1',
  '1',
  '12/30/1899 1:04:35 AM',
  'M',
  'Kirui, Geoffrey',
  '1',
  '12/30/1899 2:09:37 AM',
  '1',
  '12/30/1899 12:04:57 AM',
  ''],
 ['12/30/1899 12:30:27 AM',
  '12/30/1899 12:45:44 AM',
  '12/30/1899 1:01:15 AM',
  '12/30/1899 1:16:59 AM',
  '12/30/1899 1:33:01 AM',
  '12/30/1899 1:48:19 AM',
  '12/30/1899 2:03:14 AM',
  '12/30/1899 12:15:24 AM',
  '30',
  '17',
  '7798',
  'USA',
  '7798',
  '',
  'Portland',
  'USA',
  '2',
  '2',
  '12/30/1899 1:04:35 AM',
  'M',
  'Rupp, Galen',
  '1',
  '12/30/1899 2:09:58 AM',
  '2',
  '12/30/1899 12:04:58 AM',
  'OR'],
 ['12/30/1899 12:30:29 AM',
  '12/30/1899 12:45:44 AM',
  '12/30/1899 1:01:16 AM',
  '12/30/1899 1:17:00 AM',
  '12/30/1899 1:

#### Loading a CSV's Data 

In [153]:
FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

# i = integer, f = float, |s25 = string with 25 characters
DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

# instead of loading csv normally, let's load it into a numpy array to calculate results on

def load_data(filename, d = ','):
    data = np.genfromtxt(filename, delimiter = d, skip_header = 1,
                        usecols = np.arange(0,23), invalid_raise = False,
                        names = FIELDS, dtype = DATATYPES)
    return data

bs2017 = load_data('../files/redsox_2017_hitting.txt')
bs2017

names = bs2017['Name']
hits = bs2017['H']
print(names)

for i in range(len(names)):
    print(f'{names[i]} had {hits[i]} hits')
    


[b'Christian Vazquez' b'Mitch Moreland' b'Dustin Pedroia'
 b'Xander Bogaerts' b'Rafael Devers' b'Andrew Benintendi'
 b'Jackie Bradley Jr.' b'Mookie Betts' b'Hanley Ramirez' b'Sandy Leon'
 b'Chris Young' b'Deven Marrero' b'Eduardo Nunez' b'Brock Holt'
 b'Josh Rutledge' b'Pablo Sandoval' b'Sam Travis' b'Tzu-Wei Lin'
 b'Marco Hernandez' b'Rajai Davis' b'Steve Selsky' b'Blake Swihart'
 b"Chase d'Arnaud"]
b'Christian Vazquez' had 94 hits
b'Mitch Moreland' had 125 hits
b'Dustin Pedroia' had 119 hits
b'Xander Bogaerts' had 156 hits
b'Rafael Devers' had 63 hits
b'Andrew Benintendi' had 155 hits
b'Jackie Bradley Jr.' had 118 hits
b'Mookie Betts' had 166 hits
b'Hanley Ramirez' had 120 hits
b'Sandy Leon' had 61 hits
b'Chris Young' had 57 hits
b'Deven Marrero' had 36 hits
b'Eduardo Nunez' had 53 hits
b'Brock Holt' had 28 hits
b'Josh Rutledge' had 24 hits
b'Pablo Sandoval' had 21 hits
b'Sam Travis' had 20 hits
b'Tzu-Wei Lin' had 15 hits
b'Marco Hernandez' had 16 hits
b'Rajai Davis' had 9 hits
b'Ste

#### Summing the top 5 hitters for HR's

In [170]:
# find the top 5 hr hitters

# Step 1: Get all HR data into a variable
# Step 2: Get all Player Names
# Step 3: Create new list for new_names (empty to start)
# Step 4: Decode the player names into regular strings
# Step 5: Grab all data and place inside of a zipped list
# Step 6: Sort values based on HR data

# Step 1
home_runs = bs2017['HR']

# Step 2
player_names = bs2017['Name']

# Step 3
new_names = []

# Step 4
for name in player_names:
    new_names.append(name.decode('utf-8'))


print(new_names)

# Step 5

zipped_values = list(zip(new_names, home_runs))
print(zipped_values)
# for i in range(len(new_names)):
#     zipped_values.append((new_names[i], home_runs[i]))
print(zipped_values)

# Step 6

sorted_hr = sorted(zipped_values, key = lambda x: x[1], reverse=True)
sorted_hr[0:6]

['Christian Vazquez', 'Mitch Moreland', 'Dustin Pedroia', 'Xander Bogaerts', 'Rafael Devers', 'Andrew Benintendi', 'Jackie Bradley Jr.', 'Mookie Betts', 'Hanley Ramirez', 'Sandy Leon', 'Chris Young', 'Deven Marrero', 'Eduardo Nunez', 'Brock Holt', 'Josh Rutledge', 'Pablo Sandoval', 'Sam Travis', 'Tzu-Wei Lin', 'Marco Hernandez', 'Rajai Davis', 'Steve Selsky', 'Blake Swihart', "Chase d'Arnaud"]
[('Christian Vazquez', 5), ('Mitch Moreland', 22), ('Dustin Pedroia', 7), ('Xander Bogaerts', 10), ('Rafael Devers', 10), ('Andrew Benintendi', 20), ('Jackie Bradley Jr.', 17), ('Mookie Betts', 24), ('Hanley Ramirez', 23), ('Sandy Leon', 7), ('Chris Young', 7), ('Deven Marrero', 4), ('Eduardo Nunez', 8), ('Brock Holt', 0), ('Josh Rutledge', 0), ('Pablo Sandoval', 4), ('Sam Travis', 0), ('Tzu-Wei Lin', 0), ('Marco Hernandez', 0), ('Rajai Davis', 0), ('Steve Selsky', 0), ('Blake Swihart', 0), ("Chase d'Arnaud", 0)]
[('Christian Vazquez', 5), ('Mitch Moreland', 22), ('Dustin Pedroia', 7), ('Xander B

[('Mookie Betts', 24),
 ('Hanley Ramirez', 23),
 ('Mitch Moreland', 22),
 ('Andrew Benintendi', 20),
 ('Jackie Bradley Jr.', 17),
 ('Xander Bogaerts', 10)]

# Exercises To Complete.... <br>
1 - Calculate the BMI (body mass index) on the two lists below using NDArrays.


In [8]:
import numpy as np
# formula = weight / (height**2) * 730
height = np.array([69, 70, 71, 72, 73, 74, 75])
weight = np.array([110, 120, 130, 140, 150, 160, 170])

# OUTPUT: [16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
# 22.06222222]
result = weight / (height*height) * 730
print(result)

[16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
 22.06222222]


2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [23]:
"""
Example Result
array([[14.21633515,  7.98846653,  9.64140715],
       [ 6.30982234,  9.96414331,  8.43153688],
       [14.73102068, 11.76072894, 14.23356121]])
"""
#def makeMatrix(low,high,shape,data_type = float): -- Example


def makeMatrix(low, high, shape, data_type):
    if data_type == 'int':
        print('Here is your random matrix of integers: \n %s' % np.random.randint(low, high, (shape)))
    else:
        print('\nHere is your random matrix of floating numbers: \n %s' % np.random.uniform(low, high, (shape)))
        
makeMatrix(3,96,(4,3),'int')
makeMatrix(5,26,(5,5),'float')

Here is your random matrix of integers: 
 [[12 29 32]
 [21 89 51]
 [17 35 91]
 [47 75 41]]

Here is your random matrix of floating numbers: 
 [[20.52783272 15.77693029  5.64716949  7.70511037  7.68481333]
 [15.06240963 12.79524252 18.26709336 14.78084178 25.26535688]
 [18.68845899 20.1408814   6.18823008 11.90225684  7.86360848]
 [20.94812282 18.51683092  8.8639557  12.8913426   6.81002749]
 [18.42766477 10.58116947  9.55186166 25.70315659 15.86698132]]


3 - Extra: Open and load the data in the two text files that have the Boston Red Sox hitting data for the past seasons. Compare the difference in the two years by putting the data into an NDArray and running a differencial operation on it. The column to look for will be SLG.
Your output should display which year (either 2017 or 2018) was a better year based on SLG

In [25]:
import csv
import numpy as np

#Test to make sure you have the correct data




In [89]:
"""
Example Result - Not the actual result
Boston 18 had more SLG in 2018
[0.404 0.443 0.392 0.403 0.482 0.424 0.402 0.459 0.429 0.354 0.387 0.333
 0.539 0.243 0.262 0.354 0.342 0.339 0.328 0.306 0.222 0.2   1.   ]
"""

FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

#Use this function to actually open the data inside of a NDArray

def load_data(filename, d = ','):
    data = np.genfromtxt(filename, delimiter = d, skip_header = 1,
                        usecols = np.arange(0,23), invalid_raise = False,
                        names = FIELDS, dtype = DATATYPES)
    return data

bs2017 = load_data('../files/redsox_2017_hitting.txt')
bs2018 = load_data('../files/redsox_2018_hitting.txt')

#ONE method, based on the slg formula and total bases and attempts from data.
check_ans = sum(bs2017['R'])+sum(bs2017['2B']*2)+sum(bs2017['3B']*3)+sum(bs2017['HR']*4)
real_slg_2017=(check_ans/sum(bs2017['AB']))
#print(real_slg_2017)

check_ans2 = sum(bs2018['R'])+sum(bs2018['2B']*2)+sum(bs2018['3B']*3)+sum(bs2018['HR']*4)
real_slg_2018=(check_ans2/sum(bs2018['AB']))
#print(real_slg_2018)

def better_slg1(year_1, year_2):
    if year_1 > year_2:
        print(f'Boston had a better SLG in 2017: {year_1} compared to {year_2}')
    else:
        print(f'Boston had a better SLG in 2018: {year_2} compared to {year_1}')

print(better_slg1(real_slg_2017, real_slg_2018))
                                
    
    
#ANOTHER method, based on averaging individual slg per year, and based on example result given at top of cell.

slg_2017 = bs2017['SLG']
slg_2018 = bs2017['SLG']
#print(slg_2018)
# print(sum(slg_2017))
# print(len(slg_2017))
# print(sum(slg_2017)/len(slg_2017))

def better_slg2(year_a, year_b):
    
    if sum(year_a) / len(year_a) > sum(year_b) / len(year_b):
        print(f'Boston had a better SLG in 2017: {slg_2017}')
    else:
        print(f'Boston had a better SLG in 2018: {slg_2018}')
print(better_slg(slg_2017, slg_2018))

Boston had a better SLG in 2018: 0.4466452533904354 compared to 0.3747122365857978
None
Boston had a better SLG in 2018: [0.404 0.443 0.392 0.403 0.482 0.424 0.402 0.459 0.429 0.354 0.387 0.333
 0.539 0.243 0.262 0.354 0.342 0.339 0.328 0.306 0.222 0.2   1.   ]
None
